import { ArrowRight,ChevronDown,Code2,Download,FileCode2,FolderGit2,Plus,Send,Settings2,ShieldCheck,Sparkles,Terminal,X } from 'lucide-react';
import React,{ useEffect,useRef,useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { PRODUCT } from '../../config/product';

export function CodeWorkspace() {
  const navigate=useNavigate();
  const [file,setFile]=useState(false);
  const [welcome,setWelcome]=useState(true);
  const [code,setCode]=useState('');
  const [name,setName]=useState('untitled.ts');
  const [panel,setPanel]=useState('assistant');
  const [input,setInput]=useState('');
  const [messages,setMessages]=useState<{sender:string;text:string}[]>([]);
  const [busy,setBusy]=useState(false);
  const [error,setError]=useState('');
  const [modelOpen,setModelOpen]=useState(false);
  const inputRef=useRef<HTMLTextAreaElement>(null);
  const messageEnd=useRef<HTMLDivElement>(null);
  useEffect(()=>{messageEnd.current?.scrollIntoView({behavior:'smooth',block:'nearest'});},[messages,busy]);
  const create=()=>{setFile(true);setWelcome(false);};
  const closeFile=()=>{if(code&&!window.confirm('Close this file? Download it first if you want to keep your changes.'))return;setFile(false);setWelcome(true);setCode('');};
  const send=async(e:React.FormEvent)=>{e.preventDefault();if(!input.trim()||busy)return;const next=[...messages,{sender:'user',text:input.trim()}];setMessages(next);setInput('');setBusy(true);setError('');try{const res=await fetch('/api/ai/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({messages:next,...(file?{activeFile:{path:name,content:code}}:{})}),signal:AbortSignal.timeout(60000)});const data=await res.json();if(!res.ok)throw new Error(data.error||'The assistant could not respond.');setMessages([...next,{sender:'assistant',text:data.reply}]);}catch{setError('The assistant is unavailable. Check your server’s AI configuration and try again.');}finally{setBusy(false);}};
  const download=()=>{const url=URL.createObjectURL(new Blob([code],{type:'text/plain'}));const a=document.createElement('a');a.href=url;a.download=name||'untitled.ts';a.click();URL.revokeObjectURL(url);};
  return <div className="oc-workspace"><section className="oc-editor-panel" aria-label="Code workspace"><div className="oc-tabbar"><button className="oc-icon oc-new-tab" aria-label="Create new file" onClick={create}><Plus size={18}/></button>{(welcome||file)&&<div className="oc-editor-tab"><FileCode2 size={14}/><span>{file?name:'Welcome'}</span><button className="oc-icon" aria-label={file?'Close file':'Close Welcome tab'} onClick={()=>file?closeFile():setWelcome(false)}><X size={13}/></button></div>}<span className="oc-tabbar-spacer"/>{file&&<button className="oc-download" onClick={download}><Download size={14}/>Save file</button>}<span className="oc-editor-dots">•••</span></div>
      {file?<div className="oc-file-editor"><label className="oc-filename">File name<input aria-label="File name" value={name} onChange={e=>setName(e.target.value)}/><span>Local draft</span></label><textarea autoFocus spellCheck={false} aria-label="Code editor" value={code} onChange={e=>setCode(e.target.value)} placeholder="// Start writing something great…"/><div className="oc-editor-status"><span>UTF-8</span><span>{code.split('\n').length} lines</span><span>Changes stay in this tab until downloaded</span></div></div>:welcome?<div className="oc-welcome"><div className="oc-welcome-inner"><div className="oc-code-emblem"><Code2 size={31} strokeWidth={1.5}/></div><h1>Start coding with<br className="oc-heading-break"/> <span>confidence.</span></h1><p>Open a repository, start writing code, or run a scan<br className="oc-copy-break"/> to get AI-powered insights.</p><div className="oc-start-actions"><button onClick={()=>navigate('/repo')}><FolderGit2 size={20}/><span>Open Repository</span><ArrowRight size={17}/></button><button onClick={create}><FileCode2 size={20}/><span>Create New File</span><ArrowRight size={17}/></button><button onClick={()=>navigate('/review/scan')}><ShieldCheck size={20}/><span>Run Security Scan</span><ArrowRight size={17}/></button></div><div className="oc-welcome-hint"><kbd>⌘ K</kbd><span>A shortcut to everything.</span></div></div></div>:<div className="oc-empty"><Code2 size={30}/><p>A clear canvas for your next idea.</p><button onClick={()=>setWelcome(true)}>Open Welcome</button></div>}
      <div className="oc-panel-foot"><span><span className="oc-dot"/>Ready when you are</span><span>Build. Secure. Ship.</span></div>
    </section><aside className="oc-ai-panel" aria-label="AI coding assistant"><div className="oc-ai-tabs" role="tablist"><button role="tab" aria-selected={panel==='assistant'} className={panel==='assistant'?'active':''} onClick={()=>setPanel('assistant')}><Sparkles size={15}/>AI Assistant</button><button role="tab" aria-selected={panel==='analysis'} className={panel==='analysis'?'active':''} onClick={()=>setPanel('analysis')}>Analysis</button><button className="oc-icon" aria-label="Assistant model settings" onClick={()=>setModelOpen(!modelOpen)}><Settings2 size={16}/></button></div>{panel==='assistant'?<><div className="oc-ai-content">{messages.length?<div className="oc-messages" aria-live="polite">{messages.map((m,i)=><div key={i} className={`oc-message ${m.sender}`}><strong>{m.sender==='user'?'You':'OminiCode'}</strong><p>{m.text}</p></div>)}{busy&&<p className="oc-thinking">Thinking…</p>}<div ref={messageEnd}/></div>:<div className="oc-ai-intro"><div className="oc-sparkle"><Sparkles size={30} strokeWidth={1.4}/></div><h2>Your AI pair programmer.</h2><p>Get code explanations, fix issues, write tests,<br/> and more — right in your workflow.</p><div className="oc-prompts">{[[Code2,'Explain this code'],[ShieldCheck,'Find security issues'],[Sparkles,'Suggest a fix'],[Terminal,'Generate tests']].map(([Icon,label])=>{const I=Icon as typeof Code2;return <button key={String(label)} onClick={()=>{setInput(String(label)+(file?' in '+name:'.'));inputRef.current?.focus();}}><I size={16}/>{String(label)}<ArrowRight size={13}/></button>;})}</div></div>}</div><div className="oc-composer-area">{error&&<p className="oc-error" role="alert">{error}</p>}<form className="oc-composer" onSubmit={send}><textarea ref={inputRef} aria-label="Message OminiCode" value={input} onChange={e=>setInput(e.target.value)} placeholder="Ask OminiCode anything…" rows={2} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();e.currentTarget.form?.requestSubmit();}}}/><div><span>{file?<><FileCode2 size={11}/>{name}</>:'Your next idea starts here'}</span><button type="submit" aria-label="Send message" disabled={busy||!input.trim()}><Send size={15}/></button></div></form><div className="oc-model-row"><button onClick={()=>setModelOpen(!modelOpen)} aria-expanded={modelOpen}><Sparkles size={12}/>{PRODUCT.defaultAiModelLabel}<ChevronDown size={12}/></button><span>↵ to send</span></div></div></>:<div className="oc-analysis"><ShieldCheck size={31}/><h2>Your next insight starts here.</h2><p>Run a code scan to inspect findings and suggested fixes in the analysis workspace.</p><button className="oc-solid" onClick={()=>navigate('/review/scan')}>Open scanner<ArrowRight size={15}/></button></div>}{modelOpen&&<div className="oc-model-popover"><strong>Assistant model</strong><p>{PRODUCT.defaultAiModelLabel} · Groq <span>Active</span></p><p className="oc-unavailable">GPT-4o <span>Not configured</span></p><small>Models are configured on the server.</small></div>}</aside></div>;
}
